apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: demucs-worker
spec:
  selector:
    matchLabels:
      app: demucs-worker
  replicas: 1
  template:
    metadata:
      labels:
        app: demucs-worker
    spec:
      containers:
      - name: demucs-worker
        image: sohank17/demucs-worker:v4
        imagePullPolicy: Always
        # resources:
        #   requests:
        #     cpu: 1000m
        #     memory: 2000Mi
        env:
        - name: REDIS_HOST
          value: "redis.redis.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_HOST
          value: "minio-proj.minio.svc.cluster.local:9000"
